"""caching_of_avatar_hashes

Revision ID: 1a8afad294a2
Revises: d66f086b258
Create Date: 2016-06-03 14:54:26.632000

"""

# revision identifiers, used by Alembic.
revision = '1a8afad294a2'
down_revision = 'd66f086b258'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
