"""rich_text_posts

Revision ID: 1e5ec550379d
Revises: 57cd35fb979d
Create Date: 2016-06-04 21:42:36.794000

"""

# revision identifiers, used by Alembic.
revision = '1e5ec550379d'
down_revision = '57cd35fb979d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
